### ISSUE TITLE
Could not open input file: k61v1injector.php

### ISSUE THREAD

**Issue by Omarelwi** [MlgmXyysd/k61v1injector#4]
We I open the script I got this message:
Could not open input file: k61v1injector.php
cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: No connection could be made because the target machine actively refused it. (10061)

But the device is connected and recognized with the external adb

**Comment by MlgmXyysd** [comment]
It seems to be a PHP configuration problem, which has nothing to do with this project.
